

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../index.css"
import { Header } from "@/components/header";

const inter = Inter({

  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Safe Money",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col h-[100vh]  ${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
